project:
  type: website
  output-dir: docs

lang: fr

website:
  title: "Presque 50 ans de recherche universitaire du jeu de rôle sur table : évolution historique et analyse bibliométrique"
  navbar:
    left:
      - href: index.qmd
        text: fr
      - href: index-english.qmd
        text: en
      - href: about.qmd
        text: info

format:
  html:
    theme: cosmo
    css: annexes/styles.css
    toc: true

editor: visual

